# Application Name
spring.application.name=ReWrite

# AWS Configuration (Load from Environment Variables)
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}
aws.s3.region=${AWS_REGION}
aws.s3.bucketName=${AWS_S3_BUCKET_NAME}

# Gemini API Configuration
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

# Logging
logging.level.com.lockin.rewrite=DEBUG
